#include <stdio.h>

// [Main Purpose]: The main wallet of the bank, accessible by all functions in the software.
int balance = 1000; 

// [Main Purpose]: This function strictly displays the current bank balance on the screen.
void show_balance() {
    printf("\n--------------------------------------\n");
    printf("Pratap's Bank Account Balance: INR %d\n", balance);
    printf("--------------------------------------\n");
}

// [Main Purpose]: The logic engine of the game that processes the user's bet and guess.
int play_round(int bet, int guess) {
    int secret_code = 7; // The hidden secret number generated by the computer

    // [Main Purpose]: If user's guess matches the secret code, user wins.
    if (guess == secret_code) {
        balance = balance + (bet * 2); // Double the bet money and add to total balance
        return 1; // 1 means 'Success / Win'
    } 
    // [Main Purpose]: If user's guess is wrong, user loses.
    else {
        balance = balance - bet; // Deduct the bet money from the main wallet
        return 0; // 0 means 'Failure / Loss'
    }
}

int main() {
    int choice, bet_money, user_guess;
    
    printf("=== Welcome to Pratap's Elite Casino Engine ===\n");

    // [Main Purpose]: A do-while loop to keep displaying the menu until user inputs choice 3 to exit.
    do {
        printf("\n1. Balance Check\n2. Play Game\n3. Exit Game\n");
        printf("Choose your option (1-3): ");
        scanf("%d", &choice);

        // [Main Purpose]: Directing the user input to the correct software function.
        switch(choice) {
            case 1:
                show_balance(); // Invoking the balance tracking function
                break;
                
            case 2:
                // [Main Purpose]: Capturing the betting amount and the target guessing number from user.
                printf("How much money to bet?: ");
                scanf("%d", &bet_money);
                printf("Guess a number between 1 and 10: ");
                scanf("%d", &user_guess);
                
                // [Main Purpose]: Executing the core game engine and passing arguments.
                if(play_round(bet_money, user_guess) == 1) {
                    printf("\n🎉 Congratulations Pratap! Your guess was correct! You win!\n");
                } else {
                    printf("\n❌ Sorry! Wrong guess. The stake money is gone!\n");
                }
                
                show_balance(); // Displaying updated tracking statement after the gaming round
                break;
                
            case 3:
                printf("\nExiting... Bank accounts secured safely.\n");
                break;
                
            default:
                printf("\nInvalid Option! Please choose 1, 2, or 3.\n");
        }
    } while(choice != 3); // Condition breaks immediately when choice equals 3

    printf("=== Game over! Thanks for playing Pratap's Game ===\n");
    return 0;
}
